name: Deploy to Heroku

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list
          
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          
      - name: Set Heroku config vars
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku config:set CODA_API_TOKEN=${{ secrets.CODA_API_TOKEN }} --app ${{ secrets.HEROKU_APP_NAME }}
          heroku config:set MAIN_DOC_URL=${{ secrets.MAIN_DOC_URL }} --app ${{ secrets.HEROKU_APP_NAME }}
          heroku config:set STUDENT_DOC_URL=${{ secrets.STUDENT_DOC_URL }} --app ${{ secrets.HEROKU_APP_NAME }}
          
      - name: Run database migrations
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku run python app.py --app ${{ secrets.HEROKU_APP_NAME }}
        
      - name: Start worker process
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku ps:scale worker=1 --app ${{ secrets.HEROKU_APP_NAME }} 